In [1]:
import tensorflow as tf
import numpy as np


In [2]:
t  = tf.constant([[1.,2.,3.,],[4.,5.,6.,]])
display(t)
display(t[:,1:])
display(t[...,1])

<tf.Tensor: id=0, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

<tf.Tensor: id=4, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

<tf.Tensor: id=8, shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [3]:
t  = tf.constant([[1.,2.,3.,],[4.,5.,6.,]])

# 计算
display(t+10)
display(tf.square(t))
display(t@tf.transpose(t))


<tf.Tensor: id=11, shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

<tf.Tensor: id=12, shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

<tf.Tensor: id=15, shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [6]:
print(t.numpy())
print(np.square(t))
np_t = np.array([[1.,2.,3.,],[4.,5.,6.,]])
print(tf.constant(np_t))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [8]:
#0dim,scalars
t = tf.constant(2.434)
print(t.shape)
print(t)
print(t.numpy())

()
tf.Tensor(2.434, shape=(), dtype=float32)
2.434


In [13]:
#strings
t = tf.constant('hello everyone')
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t,unit = 'UTF8_CHAR'))
print(tf.strings.unicode_decode(t, 'UTF8'))



tf.Tensor(b'hello everyone', shape=(), dtype=string)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor([104 101 108 108 111  32 101 118 101 114 121 111 110 101], shape=(14,), dtype=int32)


In [19]:
#strings array
t = tf.constant(['hello','coffee_cup','咖啡'])
print(tf.strings.length(t))
print(tf.strings.length(t,unit = 'UTF8_CHAR'))
print(tf.strings.unicode_decode(t, 'UTF8'))


tf.Tensor([ 5 10  6], shape=(3,), dtype=int32)
tf.Tensor([ 5 10  2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857]]>


In [20]:
#RaggedTensor不规则的tensot
r = tf.ragged.constant([[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857]])
print(r)
print(r[1])
print(r[1:2])


<tf.RaggedTensor [[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857]]>
tf.Tensor([ 99 111 102 102 101 101  95  99 117 112], shape=(10,), dtype=int32)
<tf.RaggedTensor [[99, 111, 102, 102, 101, 101, 95, 99, 117, 112]]>


In [26]:
# ops on ragede tensor
r2=tf.ragged.constant([[54, 45,], [], [71]])
print(tf.concat([r,r2], axis=0))
print(tf.concat([r,r2], axis=1))

<tf.RaggedTensor [[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857], [54, 45], [], [71]]>
<tf.RaggedTensor [[104, 101, 108, 108, 111, 54, 45], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857, 71]]>


In [33]:
print(r.to_tensor())#变为tensor空位用0补齐

tf.Tensor(
[[  104   101   108   108   111     0     0     0     0     0]
 [   99   111   102   102   101   101    95    99   117   112]
 [21654 21857     0     0     0     0     0     0     0     0]], shape=(3, 10), dtype=int32)


In [39]:
#sparse tensor稀疏   dense是密集的意思
s = tf.SparseTensor(indices=[[0,1],[1,0],[2,3]],#位置index必须是排号续的
                    values = [1.,2.,3.,],
                    dense_shape = [3,4]
                   )
print(s)
print(tf.sparse.to_dense(s))#转化为密集矩阵

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [42]:
# ops on sparse tensor
s2 = s *2.0
print(s2)
try:
    s3 = s+1
except TypeError as ex:
    print(TypeError)
s4 = tf.constant([[10.,20.],
                          [30.,40.],
                          [50,60],
                          [70,80]])
print(tf.sparse.sparse_dense_matmul(s,s4))#稀疏_密集_矩阵乘法

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
<class 'TypeError'>
tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]], shape=(3, 2), dtype=float32)


In [46]:
#sparse tensor稀疏   dense是密集的意思
s5 = tf.SparseTensor(indices=[[1,0],[0,1],[2,3]],#位置index必须是排好续的,
                    values = [1.,2.,3.,],
                    dense_shape = [3,4]
                   )
print(s)
s6 = tf.sparse.reorder(s5)#对sparsetensor排序
print(tf.sparse.to_dense(s6))#转化为密集矩阵

SparseTensor(indices=tf.Tensor(
[[1 0]
 [0 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 2. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [47]:
# variabies变量
v= tf.Variable([[1.,2.,3.,],[4.,5.,6.,]])
print(v)
print(v.value)
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>>
[[1. 2. 3.]
 [4. 5. 6.]]


In [55]:
# assign value给变量重新赋值，只可以用assign函数，不可以用‘=’赋值
v.assign(2*v)
print(v)
v[0,1].assign(42)
print(v)
v[1].assign([7.,8.,9.])
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 8., 84., 24.],
       [32., 40., 48.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 8., 42., 24.],
       [32., 40., 48.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 8., 42., 24.],
       [ 7.,  8.,  9.]], dtype=float32)>
