# 2-1,张量数据结构
> 程序 = 数据结构+算法。

> TensorFlow程序 = 张量数据结构 + 计算图算法语言

> 张量和计算图是 TensorFlow的核心概念。

> Tensorflow的基本数据结构是张量Tensor。张量即多维数组。Tensorflow的张量和numpy中的array很类似。

> 从行为特性来看，有两种类型的张量，常量constant和变量Variable.

> 常量的值在计算图中不可以被重新赋值，变量可以在计算图中用assign等算子重新赋值。

In [2]:
import tensorflow as tf
import numpy as np


### 1.constant

In [5]:
t  = tf.constant([[1.,2.,3.,],[4.,5.,6.,]])
display(t)
display(t[:,1:])
display(t[...,1])
display(t[:,1])

<tf.Tensor: id=17, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

<tf.Tensor: id=21, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

<tf.Tensor: id=25, shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

<tf.Tensor: id=29, shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [11]:
# t  = tf.constant([[1.,2.,3.,],[4.,5.,6.,]])

# 计算
display(t+10)
display(tf.square(t))
display(t@tf.transpose(t))


<tf.Tensor: id=31, shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

<tf.Tensor: id=32, shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

<tf.Tensor: id=35, shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [6]:
print(t.numpy())
print(np.square(t))
np_t = np.array([[1.,2.,3.,],[4.,5.,6.,]])
print(tf.constant(np_t))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [8]:
#0dim,scalars
t = tf.constant(2.434)
print(t.shape)
print(t)
print(t.numpy())

()
tf.Tensor(2.434, shape=(), dtype=float32)
2.434


In [14]:
#strings
t = tf.constant('hello everyone')
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t,unit = 'UTF8_CHAR'))
print(tf.strings.unicode_decode(t, 'UTF8'))



tf.Tensor(b'hello everyone', shape=(), dtype=string)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor([104 101 108 108 111  32 101 118 101 114 121 111 110 101], shape=(14,), dtype=int32)


In [15]:
#strings array
t = tf.constant(['hello','coffee_cup','咖啡','。'])
print(tf.strings.length(t))
print(tf.strings.length(t,unit = 'UTF8_CHAR'))
print(tf.strings.unicode_decode(t, 'UTF8'))


tf.Tensor([ 5 10  6  3], shape=(4,), dtype=int32)
tf.Tensor([ 5 10  2  1], shape=(4,), dtype=int32)
<tf.RaggedTensor [[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857], [12290]]>


### RaggedTensor
* to_tensor
* to_sparse
* to_dense

In [3]:
#RaggedTensor不规则的tensot
r = tf.ragged.constant([[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857]])
print(r)
print(r[1])
print(r[1:2])


<tf.RaggedTensor [[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857]]>
tf.Tensor([ 99 111 102 102 101 101  95  99 117 112], shape=(10,), dtype=int32)
<tf.RaggedTensor [[99, 111, 102, 102, 101, 101, 95, 99, 117, 112]]>


In [4]:
# ops on ragede tensor
r2=tf.ragged.constant([[54, 45,], [], [71]])
print(tf.concat([r,r2], axis=0))
print(tf.concat([r,r2], axis=1))

<tf.RaggedTensor [[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857], [54, 45], [], [71]]>
<tf.RaggedTensor [[104, 101, 108, 108, 111, 54, 45], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857, 71]]>


In [5]:
r3 =   tf.concat([r, r2],axis = 0)
r3

<tf.RaggedTensor [[104, 101, 108, 108, 111], [99, 111, 102, 102, 101, 101, 95, 99, 117, 112], [21654, 21857], [54, 45], [], [71]]>

In [6]:
print(r3.to_tensor())#变为tensor空位用0补齐

tf.Tensor(
[[  104   101   108   108   111     0     0     0     0     0]
 [   99   111   102   102   101   101    95    99   117   112]
 [21654 21857     0     0     0     0     0     0     0     0]
 [   54    45     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   71     0     0     0     0     0     0     0     0     0]], shape=(6, 10), dtype=int32)


In [7]:
r4 = r3.to_sparse()
print(r4)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [1 6]
 [1 7]
 [1 8]
 [1 9]
 [2 0]
 [2 1]
 [3 0]
 [3 1]
 [5 0]], shape=(20, 2), dtype=int64), values=tf.Tensor(
[  104   101   108   108   111    99   111   102   102   101   101    95
    99   117   112 21654 21857    54    45    71], shape=(20,), dtype=int32), dense_shape=tf.Tensor([ 6 10], shape=(2,), dtype=int64))


In [8]:
print(tf.sparse.to_dense(r4))

tf.Tensor(
[[  104   101   108   108   111     0     0     0     0     0]
 [   99   111   102   102   101   101    95    99   117   112]
 [21654 21857     0     0     0     0     0     0     0     0]
 [   54    45     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   71     0     0     0     0     0     0     0     0     0]], shape=(6, 10), dtype=int32)


In [10]:
#sparse tensor稀疏   dense是密集的意思
s = tf.SparseTensor(indices=[[0,1],[1,0],[2,3]],#位置index必须是排好续的
                    values = [1.,2.,3.,],
                    dense_shape = [3,4]
                   )
print(s)
print(tf.sparse.to_dense(s))#转化为密集矩阵

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


### ops on sparse tensor
* sparse_dense_matmul  稀疏_密集_矩阵乘法
* tf.sparse.reorder(s5)#对sparsetensor排序

In [11]:
# ops on sparse tensor
s2 = s *2.0
print(s2)
try:
    s3 = s+1
except TypeError as ex:
    print(TypeError)
s4 = tf.constant([[10.,20.],
                          [30.,40.],
                          [50,60],
                          [70,80]])
print(tf.sparse.sparse_dense_matmul(s,s4))#稀疏_密集_矩阵乘法

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
<class 'TypeError'>
tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]], shape=(3, 2), dtype=float32)


In [46]:
#sparse tensor稀疏   dense是密集的意思
s5 = tf.SparseTensor(indices=[[1,0],[0,1],[2,3]],#sparse.to_dense,sparse位置index必须是排好序的,
                    values = [1.,2.,3.,],
                    dense_shape = [3,4]
                   )
print(s)
s6 = tf.sparse.reorder(s5)#对sparsetensor排序
print(tf.sparse.to_dense(s6))#转化为密集矩阵

SparseTensor(indices=tf.Tensor(
[[1 0]
 [0 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 2. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


# variable 变量
## assign value给变量重新赋值，只可以用assign函数，不可以用‘=’赋值

In [13]:
# variable 变量
v= tf.Variable([[1.,2.,3.,],[4.,5.,6.,]])
print(v)
print(v.value)
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>>
[[1. 2. 3.]
 [4. 5. 6.]]


In [19]:
# assign value给变量重新赋值，只可以用assign函数，不可以用‘=’赋值
v.assign(2*v)
print(v)
v[0,1].assign(42)
print(v)
v[1].assign([7.,8.,9.])
print(v)

v.assign_add([[7.,8.,9.],[1,2,3]])
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 64.,  84., 192.],
       [ 14.,  16.,  18.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 64.,  42., 192.],
       [ 14.,  16.,  18.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 64.,  42., 192.],
       [  7.,   8.,   9.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 71.,  50., 201.],
       [  8.,  10.,  12.]], dtype=float32)>
