# 线性回归模型，自定义层次

In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import sklearn
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras
print(tf.__version__)
print(sys.version_info)
for module in np, pd ,sklearn, tf, keras:
    print(module.__name__,module.__version__)

2.0.0
sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
numpy 1.18.1
pandas 1.0.1
sklearn 0.22.2
tensorflow 2.0.0
tensorflow_core.keras 2.2.4-tf


In [5]:
layer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(100,input_shape=[None,5])
layer(tf.zeros([10,5]))
# layer可以当作函数调用输入是None*5的矩阵None是不定值，输出是100，所以输出是None值*100的矩阵，None=10
# shape=(10, 100), 

<tf.Tensor: id=87, shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 

In [6]:
# layer的方法
layer.variables
# x *w +b就是全连接层dense layer做的事情

[<tf.Variable 'dense_5/kernel:0' shape=(5, 100) dtype=float32, numpy=
 array([[-0.0775263 ,  0.01405533,  0.03453822,  0.04415034, -0.10577969,
          0.19515996,  0.14099576,  0.23275267,  0.11306225, -0.14616308,
         -0.15068445, -0.04130307,  0.20634066, -0.08791772, -0.04781081,
         -0.19852123, -0.01171798, -0.13351235,  0.18369652, -0.09781533,
         -0.10898316,  0.1960584 , -0.07301024,  0.02698199, -0.04146744,
         -0.07259442,  0.05869029,  0.02663885,  0.01857479, -0.02185616,
         -0.15174565, -0.22268693, -0.07980961,  0.1766193 , -0.20527968,
         -0.20306996,  0.20004956, -0.005353  ,  0.02246524,  0.00453408,
          0.06701885, -0.2292822 , -0.12181016, -0.00824779, -0.04028757,
         -0.1426776 , -0.18519315, -0.05168667,  0.08893673,  0.04599337,
          0.1335    , -0.07012612, -0.2230168 , -0.05762613, -0.15796626,
          0.09637712,  0.19617198,  0.02501847,  0.22990383,  0.04837607,
          0.0798694 ,  0.12160207, -0.1598

In [8]:
layer.trainable_variables
# 打印所有可训练的变量



[<tf.Variable 'dense_5/kernel:0' shape=(5, 100) dtype=float32, numpy=
 array([[-0.0775263 ,  0.01405533,  0.03453822,  0.04415034, -0.10577969,
          0.19515996,  0.14099576,  0.23275267,  0.11306225, -0.14616308,
         -0.15068445, -0.04130307,  0.20634066, -0.08791772, -0.04781081,
         -0.19852123, -0.01171798, -0.13351235,  0.18369652, -0.09781533,
         -0.10898316,  0.1960584 , -0.07301024,  0.02698199, -0.04146744,
         -0.07259442,  0.05869029,  0.02663885,  0.01857479, -0.02185616,
         -0.15174565, -0.22268693, -0.07980961,  0.1766193 , -0.20527968,
         -0.20306996,  0.20004956, -0.005353  ,  0.02246524,  0.00453408,
          0.06701885, -0.2292822 , -0.12181016, -0.00824779, -0.04028757,
         -0.1426776 , -0.18519315, -0.05168667,  0.08893673,  0.04599337,
          0.1335    , -0.07012612, -0.2230168 , -0.05762613, -0.15796626,
          0.09637712,  0.19617198,  0.02501847,  0.22990383,  0.04837607,
          0.0798694 ,  0.12160207, -0.1598

In [10]:
help(layer)

Help on Dense in module tensorflow.python.keras.layers.core object:

class Dense(tensorflow.python.keras.engine.base_layer.Layer)
 |  Dense(units, activation=None, use_bias=True, kernel_initializer='glorot_uniform', bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, bias_constraint=None, **kwargs)
 |  
 |  Just your regular densely-connected NN layer.
 |  
 |  `Dense` implements the operation:
 |  `output = activation(dot(input, kernel) + bias)`
 |  where `activation` is the element-wise activation function
 |  passed as the `activation` argument, `kernel` is a weights matrix
 |  created by the layer, and `bias` is a bias vector created by the layer
 |  (only applicable if `use_bias` is `True`).
 |  
 |  Note: If the input to the layer has a rank greater than 2, then
 |  it is flattened prior to the initial dot product with `kernel`.
 |  
 |  Example:
 |  
 |  ```python
 |  # as first layer in a sequential model:

In [13]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

# print(housing.DESCR)
print(housing.data.shape)
print(housing.target.shape)


(20640, 8)
(20640,)


In [14]:
from sklearn.model_selection import train_test_split

x_train_all,x_test,y_train_all,y_test=train_test_split(housing.data, housing.target,random_state=7)
x_train, x_valid, y_train, y_valid = train_test_split(x_train_all,y_train_all,random_state=11)

In [15]:
from sklearn.preprocessing import StandardScaler
transfer = StandardScaler()
x_train_scaled = transfer.fit_transform(x_train)
x_test_scaled = transfer.transform(x_test)
x_valid_scaled = transfer.transform(x_valid)

In [28]:
# tf.nn.softplus: log(1+e^x)
# 激活函数softplus相当于平滑版的relu
# 自定义softplus激活函数,把没有参数的激活函数变成有函数
customized_softplus = keras.layers.Lambda(lambda x : tf.nn.softplus(x))
print(customized_softplus([-10.,-5.,0.,5.,10.]))

tf.Tensor([4.5417706e-05 6.7153489e-03 6.9314718e-01 5.0067153e+00 1.0000046e+01], shape=(5,), dtype=float32)


In [31]:
#使用自定义的dense layer

class CustomizedDenseLayer(keras.layers.Layer):
    def __init__(self,units,activation=None,**kwarge):
        self.units = units
        self.activation =keras.layers.Activation(activation)
        super().__init__(**kwarge)
        
    def build(self,input_shape):
        '''构建需要的参数'''
#         x * w + b input_shape[None,a] * [a,b]-->output_shape[None,b]
        self.kernel = self.add_weight(name ='kernel',
                                                 shape = (input_shape[1],self.units),
                                                initializer = 'uniform',
                                                trainable = True)
        self.bias = self.add_weight(name ='bias',
                                                 shape = (self.units,),
                                                initializer = 'zeros',
                                                trainable = True)
        super(CustomizedDenseLayer,self).build(input_shape)

    def call(self, x):
        '''完成正向计算'''
        return self.activation(x @ self.kernel + self.bias)

model = keras.models.Sequential([
    CustomizedDenseLayer(30,activation='relu',input_shape=x_train.shape[1:]),
    CustomizedDenseLayer(1),
    customized_softplus
    #相当于
#     keras.layers.Dense(1, activation='softplus')
# 或者 keras.layers.Dense(1)
#         keras.layers.Activation('softplus')
    ])


model.compile(loss='mean_squared_error',
             optimizer = 'nadam',# SGD -> SGDM -> NAG ->AdaGrad -> AdaDelta -> Adam -> Nadam
             )
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
customized_dense_layer_10 (C (None, 30)                270       
_________________________________________________________________
customized_dense_layer_11 (C (None, 1)                 31        
_________________________________________________________________
lambda_5 (Lambda)            (None, 1)                 0         
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________


In [30]:
callbacks = [keras.callbacks.EarlyStopping(patience=5,min_delta=1e-2)]
history = model.fit(x_train_scaled,y_train,epochs=5,
                  validation_data=(x_valid_scaled,y_valid), 
                  callbacks= callbacks )

Train on 11610 samples, validate on 3870 samples
Epoch 1/5
11610/11610 [==============================] - 4s 364us/sample - loss: 1.3314 - val_loss: 0.6135
Epoch 2/5
11610/11610 [==============================] - 2s 156us/sample - loss: 0.4754 - val_loss: 0.4434
Epoch 3/5
11610/11610 [==============================] - 2s 157us/sample - loss: 0.4106 - val_loss: 0.4186
Epoch 4/5
11610/11610 [==============================] - 2s 156us/sample - loss: 0.3989 - val_loss: 0.4064
Epoch 5/5
11610/11610 [==============================] - 2s 158us/sample - loss: 0.3912 - val_loss: 0.4018


In [ ]:
def plot_learning_curves(history):
    pd.DataFrame(history.history).plot(figsize=[8,5])
    plt.grid(True)
    plt.gca().set_ylim(0,1)
    plt.show()

plot_learning_curves(history)

In [ ]:
model.evaluate(x_test_scaled, y_test, verbose=2)


In [ ]:
from scipy.stats import reciprocal
param_distribution={
    'hidden_layers': [1,2,3,4,5,],
    'layer_size': np.arange(1,100),
    'learnning_rate': reciprocal(1e-4,1e-2)
    }
from sklearn.model_selection import RandomizedSearchCV
estimator = RandomizedSearchCV(sklearn_model, #模型estimator
                                                 param_distribution,#定义好的搜索空间
                                                 n_iter = 10,#要搜索的参数集合数量
#                                                  n_jobs = 1，#并行处理数据数量
                                                  )

callbacks = [keras.callbacks.EarlyStopping(patience=5,min_delta=1e-2)]
estimator.fit(x_train_scaled,y_train,epochs=100,
                  validation_data=(x_valid_scaled,y_valid), 
                  callbacks= callbacks)

In [ ]:
# reciprocal函数演示
# from scipy.stats import reciprocal
# # f(x) = 1/(x*log(b/a))     a<x<b
# reciprocal.rvs(1e-4, 1e-2, size =10)

In [ ]:
#最佳参数
print('最佳参数：\n',estimator.best_params_)
#最佳结果
print('最佳结果:\n',estimator.best_score_)
#最佳估计器
print('最佳估计器：\n',estimator.best_estimator_)
#交叉验证结果
# print('交叉验证结果:\n',estimator.cv_results_)

In [ ]:
model = estimator.best_estimator_.model
model.evaluate(x_test_scaled, y_test)