In [ ]:
# keras常用数据集 Datasets:https://keras.io/zh/datasets/

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(5))
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int64>


In [4]:
for item in dataset:
    print(item.numpy())

0
1
2
3
4


In [6]:
#epoch每遍历一次数据叫一次epoch
#repeat epoch
#get batch 遍历时每次只取一个batch，不是全部数据
dataset = dataset.repeat(6).batch(7) #遍历6次数据，5*6=30 每次7个 30/7=4...2
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 0 1], shape=(7,), dtype=int64)
tf.Tensor([2 3 4 0 1 2 3], shape=(7,), dtype=int64)
tf.Tensor([4 0 1 2 3 4 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 4 0 1 2], shape=(7,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)


In [25]:
#interleave
#cass: 文件dataset -> 具体的数据集 interleave(交错）
dataset2 = dataset.interleave(
    lambda v:tf.data.Dataset.from_tensor_slices(v),# 1.map_fn
    cycle_length=5,# 2.cycle_length并行程度
    block_length=5,# 3.block_length,每次取的量，达到均匀混合的目的
#         num_parallel_calls=tf.data.experimental.AUTOTUNE
)
for item in dataset2.take(10):
    tf.print(item)

0
1
2
3
4
2
3
4
0
1


In [23]:
#初始化dataset，可以两个数组，数量对应
x = np.array([[2,3],[4,5],[5,6]])
y = np.array(['cat','dog','fox'])
dataset3 = tf.data.Dataset.from_tensor_slices((x, y))
tf.print(dataset3)
for item_x,item_y in dataset3.take(2):
    tf.print(item_x, item_y)

<TensorSliceDataset shapes: ((2,), ()), types: (tf.int64, tf.string)>
[2 3] "cat"
[4 5] "dog"


In [28]:
# 可以用字典初始化
dataset3 = tf.data.Dataset.from_tensor_slices({'feature':x,'label':y})

for item in dataset3:
    tf.print(item)#['feature'].nump,item['label'].numpy())

{'feature': [2 3], 'label': "cat"}
{'feature': [4 5], 'label': "dog"}
{'feature': [5 6], 'label': "fox"}
