In [ ]:
# keras常用数据集 Datasets:https://keras.io/zh/datasets/

In [26]:
import tensorflow as tf
import numpy as np

In [30]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(5))
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int64>


In [28]:
for item in dataset:
    print(item.numpy())

0
1
2
3
4


In [31]:
#epoch每遍历一次数据叫一次epoch
#repeat epoch
#get batch 每次只遍历一个batch，不是全部数据
dataset = dataset.repeat(6).batch(7) #遍历三次数据，每次7个
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 0 1], shape=(7,), dtype=int64)
tf.Tensor([2 3 4 0 1 2 3], shape=(7,), dtype=int64)
tf.Tensor([4 0 1 2 3 4 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 4 0 1 2], shape=(7,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)


In [32]:
#interleave
#cass: 文件dataset -> 具体的数据集
dataset2 = dataset.interleave(
    lambda v:tf.data.Dataset.from_tensor_slices(v),# 1.map_fn
    cycle_length=5,# 2.cycle_length并行程度
    block_length=5# 3.block_length,每次取的量，达到均匀混合的目的
)
for item in dataset2:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype

In [33]:
#初始化dataset，可以两个数组，数量对应
x = np.array([[2,3],[4,5],[5,6]])
y = np.array(['cat','dog','fox'])
dataset3 = tf.data.Dataset.from_tensor_slices((x, y))
print(dataset3)
for item_x,item_y in dataset3:
    print(item_x.numpy(), item_y.numpy())

<TensorSliceDataset shapes: ((2,), ()), types: (tf.int64, tf.string)>
[2 3] b'cat'
[4 5] b'dog'
[5 6] b'fox'


In [34]:
# 可以用字典初始化
dataset3 = tf.data.Dataset.from_tensor_slices({'feature':x,'label':y})

for item in dataset3:
    print(item['feature'].numpy(),item['label'].numpy())

[2 3] b'cat'
[4 5] b'dog'
[5 6] b'fox'
