In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
# csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/applied-dl/heart.csv')
csv_file = '/users/mac/.keras/datasets/heart.csv'

In [3]:
df = pd.read_csv(csv_file)

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [5]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

In [ ]:
# 将 thal 列（数据帧（dataframe）中的 object ）转换为离散数值。
df['thal'] = pd.Categorical(df['thal'])
# categorical  是计算一个列表型数据中的类别数，即不重复项，它返回的是一个CategoricalDtype 类型的对象
df['thal'] = df.thal.cat.codes#pandas.Series.cat.codes返回代码序列以及索引。
df['thal'] 

In [6]:
# 或者用pd.factorize将离散字符编码
aaa = pd.factorize(df['thal'])
df['thal'] = aaa[0]
df['thal']

0      0
1      1
2      2
3      1
4      1
      ..
298    0
299    2
300    2
301    2
302    2
Name: thal, Length: 303, dtype: int64

In [ ]:
# 对数据进行one_hot编码pd.get_dummies
pd.get_dummies(df['thal'])


## 使用 tf.data.Dataset 读取数据
## 使用 tf.data.Dataset.from_tensor_slices 从 pandas dataframe 中读取数值。

## 使用 tf.data.Dataset 的其中一个优势是可以允许您写一些简单而又高效的数据管道（data pipelines)。从 loading data guide 可以了解更多。

In [7]:
target = df.pop('target')
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [8]:
for feat, targ in dataset.take(5):
  print ('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   0. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   1. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   2. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   1. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   1. ], Target: 0


## 由于 pd.Series 实现了 __array__ 协议，因此几乎可以在任何使用 np.array 或 tf.Tensor 的地方透明地使用它。

In [9]:
tf.constant(df['thal'])


<tf.Tensor: id=21, shape=(303,), dtype=int32, numpy=
array([0, 1, 2, 1, 1, 1, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 0, 2, 1, 2, 1, 2, 2,
       0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       2, 0, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2,
       1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2,
       1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 2, 2, 1, 2,
       1, 1, 2, 0, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 0,
       2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 0, 2, 1, 2, 0, 2, 1,
       1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 0, 0, 2, 1, 2, 1, 0, 2, 1, 1, 0,
       2, 2, 2, 2, 1, 3, 1, 1, 1, 1, 4, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1

In [10]:
# 随机读取（shuffle）并批量处理数据集。
train_dataset = dataset.shuffle(len(df)).batch(1)


In [11]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
  ])

  model.compile(optimizer='adam',
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

model = get_compiled_model()
model.fit(train_dataset, epochs=15)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Epoch 1/15
303/303 [==============================] - 4s 14ms/step - loss: 2.0053 - accuracy: 0.6106
Epoch 2/15
303/303 [==============================] - 1s 4ms/step - loss: 0.6109 - accuracy: 0.7195
Epoch 3/15
303/303 [==============================] - 1s 4ms/step - loss: 0.6031 - accuracy: 0.7228
Epoch 4/15
303/303 [==============================] - 1s 4ms/step - loss: 0.5898 - accuracy: 0.7129
Epoch 5/15
303/303 [==============================] - 1s 4ms/step - loss: 0.5850 - accuracy: 0.7327
Epoch 6

## 代替特征列
### 将字典作为输入传输给模型就像创建 tf.keras.layers.Input 层的匹配字典一样简单，应用任何预处理并使用 functional api。 您可以使用它作为 feature columns 的替代方法。

In [12]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss='binary_crossentropy',
                   metrics=['accuracy'])

## 与 tf.data 一起使用时，保存 pd.DataFrame 列结构的最简单方法是将 pd.DataFrame 转换为 dict ，并对该字典进行切片。

In [13]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)
for dict_slice in dict_slices.take(1):
  print (dict_slice)

({'age': <tf.Tensor: id=14768, shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: id=14776, shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: id=14771, shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: id=14780, shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: id=14770, shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: id=14773, shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: id=14775, shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2,

In [15]:
model_func.fit(dict_slices, epochs=100)

Epoch 1/100
19/19 [==============================] - 0s 10ms/step - loss: 1.9245 - accuracy: 0.5314
Epoch 2/100
19/19 [==============================] - 0s 7ms/step - loss: 1.7064 - accuracy: 0.5479
Epoch 3/100
19/19 [==============================] - 0s 8ms/step - loss: 1.4638 - accuracy: 0.5545
Epoch 4/100
19/19 [==============================] - 0s 7ms/step - loss: 1.2403 - accuracy: 0.5776
Epoch 5/100
19/19 [==============================] - 0s 8ms/step - loss: 1.0457 - accuracy: 0.6007
Epoch 6/100
19/19 [==============================] - 0s 8ms/step - loss: 0.8870 - accuracy: 0.6337
Epoch 7/100
19/19 [==============================] - 0s 7ms/step - loss: 0.7642 - accuracy: 0.6832
Epoch 8/100
19/19 [==============================] - 0s 7ms/step - loss: 0.6731 - accuracy: 0.6997
Epoch 9/100
19/19 [==============================] - 0s 9ms/step - loss: 0.6078 - accuracy: 0.7294
Epoch 10/100
19/19 [==============================] - 0s 8ms/step - loss: 0.5620 - accuracy: 0.7558
Epoch 11

19/19 [==============================] - 0s 7ms/step - loss: 0.3622 - accuracy: 0.8383
Epoch 83/100
19/19 [==============================] - 0s 7ms/step - loss: 0.3620 - accuracy: 0.8383
Epoch 84/100
19/19 [==============================] - 0s 7ms/step - loss: 0.3618 - accuracy: 0.8383
Epoch 85/100
19/19 [==============================] - 0s 7ms/step - loss: 0.3616 - accuracy: 0.8383
Epoch 86/100
19/19 [==============================] - 0s 7ms/step - loss: 0.3614 - accuracy: 0.8383
Epoch 87/100
19/19 [==============================] - 0s 7ms/step - loss: 0.3612 - accuracy: 0.8383
Epoch 88/100
19/19 [==============================] - 0s 7ms/step - loss: 0.3610 - accuracy: 0.8383
Epoch 89/100
19/19 [==============================] - 0s 8ms/step - loss: 0.3609 - accuracy: 0.8383
Epoch 90/100
19/19 [==============================] - 0s 7ms/step - loss: 0.3607 - accuracy: 0.8383
Epoch 91/100
19/19 [==============================] - 0s 8ms/step - loss: 0.3605 - accuracy: 0.8383
Epoch 92/100
