In [10]:
import pandas as pd
import tensorflow as tf
import seaborn as sns

In [3]:
df = pd.read_csv('data/heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   52    1   1       118   186    0        2      190      0      0.0   
299   43    0   4       132   341    1        2      136      1      3.0   
300   65    1   4       135   254    0        2      127      0      2.8   
301   48    1   4       130   256    1        2      150      1      0.0   
302   63    0   4       150   407    0        2      154      0      4.0   

     slope  ca        thal  target  
0        3   0       fixed       0  
1        2   3      normal       1  
2        2   2  reversible       0  
3        3   0      normal       0  
4        1   0      normal       0  
..     ...  ..         ...     ...  
298      2   0       fixed       0  
299      2   0  reversible       1  
300      2   1  reversible       1  
301      1   2  reversible       1  
302      2   3  reversible       1  

[303 rows x 14 columns]

## 数据检查


In [14]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

In [19]:
df.shape

(303, 14)

## 将 thal 列（数据帧（dataframe）中的 object ）转换为离散数值。

In [22]:
df['thal'] = pd.Categorical(df['thal'])#类型转换
df['thal'] = df.thal.cat.codes#编码

In [21]:
df['thal']

0      2
1      3
2      4
3      3
4      3
      ..
298    2
299    4
300    4
301    4
302    4
Name: thal, Length: 303, dtype: int8

In [23]:
df.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

# 使用 tf.data.Dataset 读取数据
## 使用 tf.data.Dataset.from_tensor_slices 从 pandas dataframe 中读取数值。

## 使用 tf.data.Dataset 的其中一个优势是可以允许您写一些简单而又高效的数据管道（data pipelines)。从 loading data guide 可以了解更多。

In [24]:
target = df.pop('target')

In [25]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))# 从 pandas dataframe 中读取数值。

In [31]:
type(dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [26]:
for feat, targ in dataset.take(5):
  print ('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


### 由于 pd.Series 实现了 __array__ 协议，因此几乎可以在任何使用 np.array 或 tf.Tensor 的地方透明地使用它。

In [32]:
tf.constant(df['thal'])

<tf.Tensor: id=23, shape=(303,), dtype=int32, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3

In [33]:
train_dataset = dataset.shuffle(len(df)).batch(1)
#随机读取（shuffle）并批量处理数据集。



# 创建并训练模型

In [34]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
  ])

  model.compile(optimizer='adam',
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

In [35]:
model = get_compiled_model()

In [39]:
model.fit(train_dataset, epochs=15)



If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Epoch 1/15
303/303 [==============================] - 4s 13ms/step - loss: 1.8672 - accuracy: 0.6964
Epoch 2/15
303/303 [==============================] - 1s 4ms/step - loss: 0.6011 - accuracy: 0.6931
Epoch 3/15
303/303 [==============================] - 1s 4ms/step - loss: 0.5703 - accuracy: 0.7459
Epoch 4/15
303/303 [==============================] - 1s 4ms/step - loss: 0.5587 - accuracy: 0.7426
Epoch 5/15
303/303 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7426
Epoch 6

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  140       
_________________________________________________________________
dense_1 (Dense)              multiple                  110       
_________________________________________________________________
dense_2 (Dense)              multiple                  11        
Total params: 261
Trainable params: 261
Non-trainable params: 0
_________________________________________________________________


# 代替特征列

## 将字典作为输入传输给模型就像创建 tf.keras.layers.Input 层的匹配字典一样简单，应用任何预处理并使用 functional api。 您可以使用它作为 feature columns 的替代方法。

In [42]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss='binary_crossentropy',
                   metrics=['accuracy'])


## 与 tf.data 一起使用时，保存 pd.DataFrame 列结构的最简单方法是将 pd.DataFrame 转换为 dict ，并对该字典进行切片。

In [43]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [44]:
for dict_slice in dict_slices.take(1):
  print (dict_slice)

({'age': <tf.Tensor: id=14783, shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: id=14791, shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: id=14786, shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: id=14795, shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: id=14785, shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: id=14788, shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: id=14790, shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2,

In [45]:
model_func.fit(dict_slices, epochs=15)


Epoch 1/15
19/19 [==============================] - 2s 94ms/step - loss: 44.2033 - accuracy: 0.2871
Epoch 2/15
19/19 [==============================] - 0s 7ms/step - loss: 25.7273 - accuracy: 0.3333
Epoch 3/15
19/19 [==============================] - 0s 7ms/step - loss: 10.6700 - accuracy: 0.5347
Epoch 4/15
19/19 [==============================] - 0s 7ms/step - loss: 5.4293 - accuracy: 0.6700
Epoch 5/15
19/19 [==============================] - 0s 7ms/step - loss: 4.8295 - accuracy: 0.7393
Epoch 6/15
19/19 [==============================] - 0s 7ms/step - loss: 4.7538 - accuracy: 0.7426
Epoch 7/15
19/19 [==============================] - 0s 7ms/step - loss: 4.6908 - accuracy: 0.7360
Epoch 8/15
19/19 [==============================] - 0s 7ms/step - loss: 4.6287 - accuracy: 0.7195
Epoch 9/15
19/19 [==============================] - 0s 7ms/step - loss: 4.5571 - accuracy: 0.7195
Epoch 10/15
19/19 [==============================] - 0s 7ms/step - loss: 4.4795 - accuracy: 0.7195
Epoch 11/15
19/