# 4-2,张量的数学运算

张量的操作主要包括张量的结构操作和张量的数学运算。

张量结构操作诸如：张量创建，索引切片，维度变换，合并分割。

张量数学运算主要有：标量运算，向量运算，矩阵运算。另外我们会介绍张量运算的广播机制。

本篇我们介绍张量的数学运算。

### 一，标量运算

张量的数学运算符可以分为标量运算符、向量运算符、以及矩阵运算符。

加减乘除乘方，以及三角函数，指数，对数等常见函数，逻辑比较运算符等都是标量运算符。

标量运算符的特点是对张量实施逐元素运算。

有些标量运算符对常用的数学运算符进行了重载。并且支持类似numpy的广播特性。

许多标量运算符都在 tf.math模块下。

```
tf.math Functions

abs（...）：计算张量的绝对值。

accumulate_n（...）：返回张量列表的按元素求和。

acos（...）：计算x元素的acos。

acosh（...）：计算元素x的反双曲余弦值。

add（...）：按元素返回x + y。

add_n（...）：将所有输入张量逐个元素相加。

angle（...）：返回一个复数（或实数）张量的逐元素参数。

argmax（...）：返回跨张量轴的最大值的索引。

argmin（...）：返回跨张量轴的最小值的索引。

asin（...）：计算元素x的三角反正弦。

asinh（...）：计算元素x的反双曲正弦值。

atan（...）：计算x元素方向的三角逆切线。

atan2（...）：计算y / x元素方向的反正切值，并遵守参数的符号。

atanh（...）：计算元素x的反双曲正切值。

bessel_i0（...）：计算x元素的Bessel i0函数。

bessel_i0e（...）：计算x元素的Bessel i0e函数。

bessel_i1（...）：计算x元素的Bessel i1函数。

bessel_i1e（...）：计算x元素的Bessel i1e函数。

betainc（...）：计算正则化的不完整beta积分。

bincount（...）：计算整数数组中每个值的出现次数。

ceil（...）：返回不小于x的按元素最小的整数。

confusion_matrix（...）：根据预测和标签计算混淆矩阵。

conj（...）：返回复数的复共轭。

cos（...）：计算x元素的cos。

cosh（...）：计算元素x的双曲余弦值。

count_nonzero（...）：计算张量维度上的非零元素数。

cumprod（...）：计算张量x沿轴的累加积。

cumsum（...）：计算沿轴的张量x的累积和。

cumulative_logsumexp（...）：计算沿轴的张量x的累积log-sum-exp。

digamma（...）：计算Psi，Lgamma的导数（的绝对值的对数

divide（...）：计算x的Python样式除以y。

divide_no_nan（...）：计算安全除数，如果y为零，则返回0。

equal（...）：按元素返回（x == y）的真值。

erf（...）：计算x元素的高斯误差函数。

erfc（...）：计算元素x的互补误差函数。

erfinv（...）：计算反误差函数。

exp（...）：计算x元素的指数。 。

expm1（...）：计算exp（x）-1个元素。

floor（...）：返回不大于x的按元素最大的整数。

floordiv（...）：将x / y元素相除，四舍五入到最负的整数。

floormod（...）：返回元素的除法余数。当x <0 xor y <0为

Greater（...）：按元素返回（x> y）的真值。

Greater_equal（...）：逐元素返回（x> = y）的真值。

igamma（...）：计算下正则化不完全Gamma函数P（a，x）。

igammac（...）：计算上正则化的不完全Gamma函数Q（a，x）。

imag（...）：返回复数（或实数）张量的虚部。

in_top_k（...）：说出目标是否在前K个预测中。

invert_permutation（...）：计算张量的逆排列。

is_finite（...）：返回x的哪些元素是有限的。

is_inf（...）：返回x的哪些元素是Inf。

is_nan（...）：返回x的哪些元素为NaN。

is_non_decreasing（...）：如果x为非递减值，则返回True。

is_strictly_increasing（...）：如果x严格增加，则返回True。

l2_normalize（...）：使用L2范数沿尺寸轴标准化。

lbeta（...）：计算，沿最后一个维缩小。

less（...）：按元素返回（x <y）的真值。

less_equal（...）：按元素返回（x <= y）的真值。

lgamma（...）：按元素计算Gamma（x）绝对值的对数。

log（...）：计算x元素的自然对数。

log1p（...）：按元素计算（1 + x）的自然对数。

log_sigmoid（...）：计算x元素的log sigmoid。

log_softmax（...）：计算日志softmax激活。

logical_and（...）：按元素返回x和y的真值。

logical_not（...）：返回非x元素值的真值。

logical_or（...）：返回x或y元素的真值。

logical_xor（...）：逻辑XOR函数。

maximum（...）：按元素返回x和y的最大值（即x> y？x：y）。

minimum（...）：返回元素的x和y的最小值（即x <y？x：y）。

mod（...）：返回元素的除法余数。当x <0 xor y <0为

multiply（...）：按元素返回x * y。

multiple_no_nan（...）：计算x和y的乘积，如果y为零，即使x为NaN或无限，也将返回0。

ndtri（...）：计算标准法线的分位数。

negative（...）：按元素计算数值负值。

nextafter（...）：直接返回x1的下一个可表示值

not_equal（...）：按元素返回（x！= y）的真值。

polygamma（...）：计算polygamma函数。

polyval（...）：计算多项式的元素值。

pow（...）：计算一个值对另一个值的幂。

real（...）：返回复数（或实数）张量的实部。

reciprocal（...）：计算x元素的倒数。

reciprocal_no_nan（...）：在元素方面执行安全的互操作。

reduce_all（...）：计算张量维度上元素的“逻辑和”。

reduce_any（...）：计算张量维度上元素的“逻辑或”。

reduce_euclidean_norm（...）：计算张量维度上元素的欧几里得范数。

reduce_logsumexp（...）：计算log（sum（exp（横跨张量维的元素）））。

reduce_max（...）：计算张量维度上的元素最大值。

reduce_mean（...）：计算张量维度上元素的均值。

reduce_min（...）：计算张量维度上的最小元素。

reduce_prod（...）：计算张量维度上元素的乘积。

reduce_std（...）：计算张量维度上元素的标准偏差。

reduce_sum（...）：计算张量维度上的元素之和。

reduce_variance（...）：计算张量维度上元素的方差。

rint（...）：返回最接近x的按元素整数。

round（...）：将张量的值四舍五入为最接近的整数（逐元素）。

rsqrt（...）：计算元素x的平方根的倒数。

scalar_mul（...）：将标量乘以Tensor或IndexedSlices对象。

segment_max（...）：计算沿张量线段的最大值。

segment_mean（...）：计算张量各段的均值。

segment_min（...）：计算沿张量线段的最小值。

segment_prod（...）：沿着张量的分段计算乘积。

segment_sum（...）：计算张量各段的和。

sigmoid（...）：计算x元素的S形。

sign（...）：返回数字符号的逐元素指示。

sin（...）：计算x元素正弦值。

sinh（...）：计算元素x的双曲正弦值。

softmax（...）：计算softmax激活。

softplus（...）：计算softplus：log（exp（features）+ 1）。

softsign（...）：计算softsign：功能/（abs（features）+ 1）。

sqrt（...）：计算元素x的平方根。

square（...）：计算元素x的平方。

squared_difference（...）：按元素返回（x-y）（x-y）。

subtract（...）：返回x-y元素级。

tan（...）：计算x元素的tan。

tanh（...）：计算元素x的双曲正切值。

top_k（...）：查找最后一个维度的k个最大条目的值和索引。

truediv（...）：按元素划分x / y（使用Python 3除法运算符语义）。

unsorted_segment_max（...）：计算沿张量线段的最大值。

unsorted_segment_mean（...）：计算沿张量线段的均值。

unsorted_segment_min（...）：计算沿张量线段的最小值。

unsorted_segment_prod（...）：沿着张量的分段计算乘积。

unsorted_segment_sqrt_n（...）：计算张量的各部分之和除以sqrt（N）。

unsorted_segment_sum（...）：计算沿张量线段的和。

xdivy（...）：如果x == 0，则返回0，否则，按元素方式返回x / y。

xlogy（...）：如果x == 0，则返回0；否则，按元素方式返回x * log（y）。

zero_fraction（...）：返回值中零的分数。

zeta（...）：计算Hurwitz zeta函数。


```


In [1]:
import tensorflow as tf 
import numpy as np 

In [ ]:
tf.math.add()

In [ ]:
a = tf.constant([[1.0,2],[-3,4.0]])
b = tf.constant([[5.0,6],[7.0,8.0]])
a+b  #运算符重载==tf.math.add(a,b)

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [ 4., 12.]], dtype=float32)>
```

In [ ]:
a-b 

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ -4.,  -4.],
       [-10.,  -4.]], dtype=float32)>
```

In [ ]:
a*b 

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[  5.,  12.],
       [-21.,  32.]], dtype=float32)>
```

In [ ]:
a/b

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.2       ,  0.33333334],
       [-0.42857143,  0.5       ]], dtype=float32)>
```

In [ ]:
a**2

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  4.],
       [ 9., 16.]], dtype=float32)>
```

In [ ]:
a**(0.5)

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [      nan, 2.       ]], dtype=float32)>
```

In [ ]:
a%3 #mod的运算符重载，等价于m = tf.math.mod(a,3)

```
<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 0], dtype=int32)>
```

In [ ]:
a//3  #地板除法

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  0.],
       [-1.,  1.]], dtype=float32)>
```

In [ ]:
(a>=2)

```
<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False,  True]])>
```

In [ ]:
(a>=2)&(a<=3)

```
<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False, False]])>
```

In [ ]:
(a>=2)|(a<=3)

```
<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>
```

In [ ]:
a==5 #tf.equal(a,5)

```
<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False, False, False])>
```

In [ ]:
tf.sqrt(a)

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [      nan, 2.       ]], dtype=float32)>
```

In [ ]:
a = tf.constant([1.0,8.0])
b = tf.constant([5.0,6.0])
c = tf.constant([6.0,7.0])
tf.add_n([a,b,c])

```
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12., 21.], dtype=float32)>
```

In [ ]:
tf.print(tf.maximum(a,b))

```
[5 8]
```

In [ ]:
tf.print(tf.minimum(a,b))

```
[1 6]
```

### 二，向量运算

```
向量运算符只在一个特定轴上运算，将一个向量映射到一个标量或者另外一个向量。
许多向量运算符都以reduce开头。区别于 np.sum()等不加reduce
```

In [2]:
#向量reduce
a = tf.range(1,10)
tf.print(tf.reduce_sum(a))
tf.print(tf.reduce_mean(a))
tf.print(tf.reduce_max(a))
tf.print(tf.reduce_min(a))
tf.print(tf.reduce_prod(a))

45
5
9
1
362880


In [4]:
np.sum(a)

45

In [ ]:
#张量指定维度进行reduce
b = tf.reshape(a,(3,3))
tf.print(tf.reduce_sum(b, axis=1, keepdims=True))
tf.print(tf.reduce_sum(b, axis=0, keepdims=True))

```
[[6]
 [15]
 [24]]
[[12 15 18]]
```

In [ ]:
#bool类型的reduce
p = tf.constant([True,False,False])
q = tf.constant([False,False,True])
tf.print(tf.reduce_all(p))
tf.print(tf.reduce_any(q))

```
0
1
```

In [ ]:
#利用tf.foldr实现tf.reduce_sum
s = tf.foldr(lambda a,b:a+b,tf.range(10)) 
tf.print(s)

```
45
```

In [ ]:
#cum扫描累积
a = tf.range(1,10)
tf.print(tf.math.cumsum(a))
tf.print(tf.math.cumprod(a))

```
[1 3 6 ... 28 36 45]
[1 2 6 ... 5040 40320 362880]
```

In [5]:
#arg最大最小值索引
a = tf.range(1,10)
tf.print(tf.argmax(a))
tf.print(tf.argmin(a))

8
0


```
8
0
```

In [13]:
#tf.math.top_k可以用于对张量排序
a = tf.constant([1,3,7,5,4,8])

values,indices = tf.math.top_k(a,3)# k=3返回的是最后一个维度3个最大的数以及这三个数的索引
tf.print(values)
tf.print(indices)

#利用tf.math.top_k可以在TensorFlow中实现KNN算法

[8 7 5]
[5 2 3]


In [22]:
a = tf.random.uniform([7,4,5],0,60, dtype = tf.int32)
tf.print(a)
values,indices = tf.math.top_k(a,3)# k=3返回的是最后一个维度3个最大的数以及这三个数的索引
tf.print(values)
tf.print(indices)


[[[29 5 36 45 35]
  [13 11 27 26 42]
  [0 51 10 12 55]
  [48 27 3 8 42]]

 [[35 31 43 49 53]
  [4 20 11 46 12]
  [45 44 41 24 35]
  [14 53 1 45 37]]

 [[32 19 59 15 57]
  [19 43 16 34 23]
  [26 33 59 29 46]
  [27 11 54 47 52]]

 ...

 [[38 38 17 18 57]
  [10 30 32 31 48]
  [11 35 25 50 31]
  [27 53 45 26 58]]

 [[29 43 42 1 26]
  [49 49 12 6 53]
  [40 46 43 25 13]
  [33 17 57 27 45]]

 [[34 59 14 34 28]
  [55 57 10 54 27]
  [18 31 39 44 16]
  [24 15 25 55 33]]]
[[[45 36 35]
  [42 27 26]
  [55 51 12]
  [48 42 27]]

 [[53 49 43]
  [46 20 12]
  [45 44 41]
  [53 45 37]]

 [[59 57 32]
  [43 34 23]
  [59 46 33]
  [54 52 47]]

 ...

 [[57 38 38]
  [48 32 31]
  [50 35 31]
  [58 53 45]]

 [[43 42 29]
  [53 49 49]
  [46 43 40]
  [57 45 33]]

 [[59 34 34]
  [57 55 54]
  [44 39 31]
  [55 33 25]]]
[[[3 2 4]
  [4 2 3]
  [4 1 3]
  [0 4 1]]

 [[4 3 2]
  [3 1 4]
  [0 1 2]
  [1 3 4]]

 [[2 4 0]
  [1 3 4]
  [2 4 1]
  [2 4 3]]

 ...

 [[4 0 1]
  [4 2 3]
  [3 1 4]
  [4 1 2]]

 [[1 2 0]
  [4 0 1]
  [1 2 0]


### 三，矩阵运算

矩阵必须是二维的。类似tf.constant([1,2,3])这样的不是矩阵。

矩阵运算包括：矩阵乘法，矩阵转置，矩阵逆，矩阵求迹，矩阵范数，矩阵行列式，矩阵求特征值，矩阵分解等运算。

除了一些常用的运算外，大部分和矩阵有关的运算都在tf.linalg子包中。

In [ ]:
#矩阵乘法
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[2,0],[0,2]])
a@b  #等价于tf.matmul(a,b)

```
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>
```

In [ ]:
#矩阵转置
a = tf.constant([[1.0,2],[3,4]])
tf.transpose(a)

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [2., 4.]], dtype=float32)>
```

In [23]:
#矩阵逆，必须为tf.float32或tf.double类型
a = tf.constant([[1.0,2],[3.0,4]],dtype = tf.float32)
tf.print(tf.linalg.inv(a))

[[-2.00000024 1.00000012]
 [1.50000012 -0.50000006]]


In [24]:
#矩阵求trace
# 在线性代数中，一个n×n矩阵A的主对角线（从左上方至右下方的对角线）上各个元素的总和被称为矩阵A的迹（或迹数），一般记作tr(A)。
a = tf.constant([[1.0,2],[3,4]])
tf.print(tf.linalg.trace(a))

5


In [25]:
#矩阵求范数
a = tf.constant([[1.0,2],[3,4]])
tf.print(tf.linalg.norm(a))

5.47722578


In [26]:
#矩阵行列式
a = tf.constant([[1.0,2],[3,4]])
tf.print(tf.linalg.det(a))

-2


In [ ]:
#矩阵特征值
tf.linalg.eigvalsh(a)

```
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.8541021,  5.854102 ], dtype=float32)>
```

In [ ]:
#矩阵qr分解
a  = tf.constant([[1.0,2.0],[3.0,4.0]],dtype = tf.float32)
q,r = tf.linalg.qr(a)
tf.print(q)
tf.print(r)
tf.print(q@r)

```
[[-0.316227794 -0.948683321]
 [-0.948683321 0.316227734]]
[[-3.1622777 -4.4271884]
 [0 -0.632455349]]
[[1.00000012 1.99999976]
 [3 4]]
```

In [ ]:
#矩阵svd分解
a  = tf.constant([[1.0,2.0],[3.0,4.0]],dtype = tf.float32)
v,s,d = tf.linalg.svd(a)
tf.matmul(tf.matmul(s,tf.linalg.diag(v)),d)

#利用svd分解可以在TensorFlow中实现主成分分析降维


```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.9999996, 1.9999996],
       [2.9999998, 4.       ]], dtype=float32)>
```

### 四，广播机制

TensorFlow的广播规则和numpy是一样的:

* 1、如果张量的维度不同，将维度较小的张量进行扩展，直到两个张量的维度都一样。
* 2、如果两个张量在某个维度上的长度是相同的，或者其中一个张量在该维度上的长度为1，那么我们就说这两个张量在该维度上是相容的。
* 3、如果两个张量在所有维度上都是相容的，它们就能使用广播。
* 4、广播之后，每个维度的长度将取两个张量在该维度长度的较大值。
* 5、在任何一个维度上，如果一个张量的长度为1，另一个张量长度大于1，那么在该维度上，就好像是对第一个张量进行了复制。

tf.broadcast_to 以显式的方式按照广播机制扩展张量的维度。

In [ ]:
a = tf.constant([1,2,3])
b = tf.constant([[0,0,0],[1,1,1],[2,2,2]])
b + a  #等价于 b + tf.broadcast_to(a,b.shape)

```
<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]], dtype=int32)>
```

In [ ]:
tf.broadcast_to(a,b.shape)

```
<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>
```

In [ ]:
#计算广播后计算结果的形状，静态形状，TensorShape类型参数
tf.broadcast_static_shape(a.shape,b.shape)

```
TensorShape([3, 3])
```

In [ ]:
#计算广播后计算结果的形状，动态形状，Tensor类型参数
c = tf.constant([1,2,3])
d = tf.constant([[1],[2],[3]])
tf.broadcast_dynamic_shape(tf.shape(c),tf.shape(d))

```
<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>
```

In [ ]:
#广播效果
c+d #等价于 tf.broadcast_to(c,[3,3]) + tf.broadcast_to(d,[3,3])

```
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6.5760484, 7.8174157],
       [6.8174157, 6.4239516]], dtype=float32)>
```

如果对本书内容理解上有需要进一步和作者交流的地方，欢迎在公众号"Python与算法之美"下留言。作者时间和精力有限，会酌情予以回复。

![image.png](./data/Python与算法之美logo.jpg)